# Generated by Django 2.0.1 on 2018-03-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns_restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gnavirestaurant',
            name='address',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='gnavirestaurant',
            name='category',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='gnavirestaurant',
            name='holiday',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='gnavirestaurant',
            name='name',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='gnavirestaurant',
            name='name_kana',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='gnavirestaurant',
            name='open_time',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='gnavirestaurant',
            name='pr_short',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='gnavirestaurant',
            name='restaurant_id',
            field=models.CharField(max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name='gnavirestaurant',
            name='tel',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='gnavirestaurant',
            name='tel_sub',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
