# Generated by Django 2.0.1 on 2018-03-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns_restaurant', '0002_auto_20180315_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gnavirestaurant',
            name='open_time',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
