# Generated by Django 2.0.1 on 2018-03-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('related_tag', models.ManyToManyField(related_name='_tag_related_tag_+', to='tag.Tag')),
            ],
        ),
    ]
