# Generated by Django 2.0.1 on 2018-03-14 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unified_restaurant', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTagLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('related_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Tag')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unified_restaurant.UnifiedRestaurant')),
            ],
        ),
    ]
