# Generated by Django 2.0.1 on 2018-03-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_restauranttaglevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttaglevel',
            name='level',
            field=models.FloatField(),
        ),
    ]
