# Generated by Django 2.0.1 on 2018-03-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_auto_20180314_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restauranttaglevel',
            old_name='related_tag',
            new_name='tag',
        ),
    ]
