# Generated by Django 2.0.1 on 2018-04-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20180419_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedrestaurant',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
