# Generated by Django 2.0.1 on 2018-03-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedrestaurant',
            name='address',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='unifiedrestaurant',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='unifiedrestaurant',
            name='name_kana',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='unifiedrestaurant',
            name='tel',
            field=models.CharField(max_length=400),
        ),
    ]
