# Generated by Django 2.0.1 on 2018-03-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_restaurant', '0003_auto_20180315_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedrestaurant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
