# Generated by Django 2.0.1 on 2018-01-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('name_kana', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('category', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('url_mobile', models.URLField()),
                ('image_url_1', models.URLField()),
                ('image_url_2', models.URLField()),
                ('address', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
                ('tel_sub', models.CharField(blank=True, max_length=200, null=True)),
                ('open_time', models.CharField(blank=True, max_length=200, null=True)),
                ('holiday', models.CharField(blank=True, max_length=200, null=True)),
                ('pr_short', models.CharField(blank=True, max_length=500, null=True)),
                ('pr_long', models.TextField(blank=True, null=True)),
                ('category_code_l', models.CharField(max_length=100)),
                ('category_name_l', models.CharField(max_length=100)),
                ('category_code_s', models.CharField(max_length=100)),
                ('category_name_s', models.CharField(max_length=100)),
                ('budget', models.CharField(blank=True, max_length=300, null=True)),
                ('party', models.CharField(blank=True, max_length=300, null=True)),
                ('lunch', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
