# Generated by Django 2.0.1 on 2018-01-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescolle_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='source_type',
            field=models.IntegerField(choices=[(1, 'GNABI')], default=1),
            preserve_default=False,
        ),
    ]
