# Generated by Django 2.0.1 on 2018-01-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescolle_view', '0002_restaurant_source_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('restaurant_id', 'source_type')},
        ),
    ]
