# Generated by Django 2.0.1 on 2018-01-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescolle_view', '0004_auto_20180130_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_json', models.TextField()),
                ('source', models.IntegerField()),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
