# Generated by Django 2.0.1 on 2018-02-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescolle_view', '0007_auto_20180204_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_kana', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
                ('gnavi_restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rescolle_view.GnaviRestaurant')),
            ],
        ),
    ]
